services:
  db:
    image: postgis/postgis
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: trends
    volumes:
    - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:

