import puppeteer from 'puppeteer';
import Base from './base.js';

class KingCounty extends Base {
    constructor(sessionId) {
        super(sessionId)
        this.name = "kingcounty";
    }

    parse(key, startUrl) {
        console.log("Crawling ", key, " ", startUrl);

        let pn = 1;
        const address = decodeURI(key);
        const splitAddr = address.split(',');
        const streetAddress = splitAddr[0];
        const city = splitAddr[1];
        const stateZipPart = splitAddr[2].split(' ');
        const zipCode = stateZipPart[stateZipPart.length - 1];

        console.log('address ', address, ', street addresss: ', streetAddress, ', city: ', city, ', zip: ', zipCode);
        (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();

            try {
                console.log('Opening first url');
                await page.goto(startUrl);

                // check to see if we have to click the checkbox
                // <input id="cphContent_checkbox_acknowledge" type="checkbox" name="kingcounty_gov$cphContent$checkbox_acknowledge" onclick="javascript:setTimeout('__doPostBack(\'king)')"
                try {
                    // wait to see if the banner pops up
                    console.log('Checking for acknowledgement banner');
                    await page.waitForSelector('td#contentcol', { timeout: 5000 });

                    const checkboxSelector = 'input#cphContent_checkbox_acknowledge';

                    // scroll checkbox into view
                    console.log('Scrolling acknowledgement banner into view');
                    await page.evaluate((checkboxSelector) => {
                        const element = document.querySelector(checkboxSelector);
                        if (element) {
                            element.scrollIntoView();
                        }
                    }, checkboxSelector);

                    console.log('Click checkbox');
                    await page.locator('input#cphContent_checkbox_acknowledge').click();
                } catch (err) {
                    console.log('Looks like there is no checkbox. Moving on: ', err);
                }

                console.log('Waiting for search page');
                await page.waitForSelector('::-p-text("Search by Address")');

                // street address input
                // <input name="kingcounty_gov$cphContent$txtAddress" type="text" id="cphContent_txtAddress" style="background-color:LightYellow;width:200px;">
                await page.locator('input#cphContent_txtAddress').fill(streetAddress);

                // city input
                // <input name="kingcounty_gov$cphContent$txtCity" type="text" id="cphContent_txtCity" style="background-color:LightYellow;">
                await page.locator('input#cphContent_txtCity').fill(city);

                // zip input
                // <input name="kingcounty_gov$cphContent$txtZip" type="text" id="cphContent_txtZip" style="background-color:LightYellow;width:74px;">
                await page.locator('input#cphContent_txtZip').fill(zipCode);

                console.log('Submitting address');
                // submit
                // <input type="submit" name="kingcounty_gov$cphContent$btn_SearchAddress" value="Search" id="cphContent_btn_SearchAddress">
                await page.locator('input#cphContent_btn_SearchAddress').click();

                // wait for detail page to load
                console.log('Waiting for details page');
                await page.waitForSelector('::-p-text("TAX ROLL HISTORY")');

                const page1 = await this.getPageResults(page);
                await this.writeOutPath(key, 1, page1.url, page1.html);
            } catch (err) {
                console.error("Something went wrong while crawling kingcounty: ", err);
                const screenshotPath = this.getScreenShotFileName(key, pn);
                console.error("Saving a screenshot: ", screenshotPath);
                await page.screenshot({ path: screenshotPath });
            }

            await browser.close();
        })();
    }

    createStartUrlPair(location) {
        const streetAddress = location.address;
        const encodedKey = encodeURI(streetAddress);
        return [
            encodedKey,
            "https://blue.kingcounty.com/Assessor/eRealProperty/default.aspx"
        ];
    }

}
new KingCounty().run();
/**
 * <table width="100%" cellspacing="0" cellpadding="0"><tbody><tr><td id="sitecontentheader" colspan="2"></td></tr><tr valign="top"><td id="contentcol" class="column">

                    <script language="javascript" type="text/javascript" src="https://www.kingcounty.gov/js/vendor/kc-analytics.js"></script>

                    <script type="text/javascript">
                          var googletag = googletag || {};
                          googletag.cmd = googletag.cmd || [];
                        (function() {
                                var gads = document.createElement('script');
                                gads.async = true;
                                gads.type = 'text/javascript';
                                var useSSL = 'https:' == document.location.protocol;
                                gads.src = (useSSL ? 'https:' : 'http:') +
                                      '//www.googletagservices.com/tag/js/gpt.js';
                            //    var node = document.getElementsByTagName('script')[0];
                            //        node.parentNode.insertBefore(gads, node);
                            //          })();
                            //          </script>
                            //
                            //          <script type="text/javascript">
                            //            googletag.cmd.push(function() {
                            //                googletag.defineSlot('/22447532351/King-County:desktop:728x90:top', [728, 90],
                            //                'div-gpt-ad-1444144432012-0').addService(googletag.pubads());
                            //                    googletag.defineSlot('/22447532351/King-County:desktop:160x600:rhs', [160, 600],
                            //                    'div-gpt-ad-1444144432012-1').addService(googletag.pubads());
                            //                        googletag.defineSlot('/22447532351/King-County:desktop:multiple-sizes:bottom', [[728, 90], [970, 90]],
                            //                        'div-gpt-ad-1444144432012-2').addService(googletag.pubads());
                            //                            googletag.pubads().enableSingleRequest();
                            //                                googletag.enableServices();
                            //                                  });
                            //                                  </script>
                            //
                            //
                            //                                  <script language="javascript" type="text/javascript">
                            //                                  // <!CDATA[
                            //                                  function printpage()
                            //                                    {
                            //                                      window.print()
                            //                                        }
                            //
                            //                                          // ]]>
                            //
                            //
                            //                                          </script>
                            //
                            //                                          <!-- /22447532351/King-County:desktop:728x90:top -->
                            //                                          <div>
                            //                                          <div id="div-gpt-ad-1444144432012-0" style="height:90px; width:728px;">
                            //                                          <script type="text/javascript">
                            //                                          googletag.cmd.push(function() { googletag.display('div-gpt-ad-1444144432012-0'); });
                            //                                          </script>
                            //                                          </div>
                            //
                            //                                          <div style="text-align: right;width:728px;">
                            //                                              <a id="cphContent_LinkButtonAds1" title="ADVERTISEMENT" href="javascript:__doPostBack('kingcounty_gov$cphContent$LinkButtonAds1','')" style="font-weight:bold;">ADVERTISEMENT</a>
                            //
                            //                                              </div>
                            //
                            //                                              </div>
                            //
                            //                                              <br>
                            //
                            //                                                <input type="hidden" name="kingcounty_gov$cphContent$hf_accept" id="cphContent_hf_accept" value="0">
                            //
                            //
                            //
                            //
                            //                                                                               <h1>eReal Property</h1>
                            //                                                                                        <div style="background-color: #f9f9f9;border:1px solid #DDDDDD; padding: 3px 10px 3px 10px;">
                            //
                            //                                                                                                             <p>
                            //                                                                                                                         In our continuing effort to provide accurate and timely information to the taxpayers
                            //                                                                                                                                     of King County, we are pleased to offer online data by entering the property
                            //                                                                                                                                                 tax account/parcel number.
                            //                                                                                                                                                             </p>
                            //                                                                                                                                                                         <p>
                            //                                                                                                                                                                                     The accuracy of the information you are accessing may be affected by changes. Therefore,
                            //                                                                                                                                                                                                 the King County Department of Assessments can not warrant the accuracy, reliability
                            //                                                                                                                                                                                                             or timeliness of the information, and shall not be held liable for losses caused
                            //                                                                                                                                                                                                                         by using this information. Any person or entity who relies on any information obtained
                            //                                                                                                                                                                                                                                     from this system, does so at their own risk.
                            //                                                                                                                                                                                                                                                 </p>
                            //
                            //                                                                                                                                                                                                                                                                         <p>
                            //                                                                                                                                                                                                                                                                                     I understand that Washington State law, RCW 42.56.070.(9) prohibits the use of lists
                            //                                                                                                                                                                                                                                                                                                 of individuals for "commercial purposes". I understand that the use for "commercial
                            //                                                                                                                                                                                                                                                                                                             purposes" of said records may also violate the rights of the individual(s) named
                            //                                                                                                                                                                                                                                                                                                                         therein and may subject me to liability for such commercial use. I understand that
                            //                                                                                                                                                                                                                                                                                                                                     "commercial purposes" means that the person requesting the record intends that the
                            //                                                                                                                                                                                                                                                                                                                                                 list will be <strong><span style="color: #a52a2a">used for general business
                            //                                                                                                                                                                                                                                                                                                                                                             purposes, including but not limited to</span></strong> communicating with the
                            //                                                                                                                                                                                                                                                                                                                                                                         individual(s) named in the record for the purpose of facilitating profit expecting
                            //                                                                                                                                                                                                                                                                                                                                                                                     activity.
                            //                                                                                                                                                                                                                                                                                                                                                                                                 </p>
                            //                                                                                                                                                                                                                                                                                                                                                                                                             <p>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                         <input id="cphContent_checkbox_acknowledge" type="checkbox" name="kingcounty_gov$cphContent$checkbox_acknowledge" onclick="javascript:setTimeout('__doPostBack(\'kingcounty_gov$cphContent$checkbox_acknowledge\',\'\')', 0)"><label for="cphContent_checkbox_acknowledge"> I acknowledge and agree to the prohibitions listed in RCW 42.56.070(9) against releasing and/or using lists of individuals for commercial purposes.</label>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                     </p>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style="font-weight: bold;background-color: #c0d7d8; border:0px; padding: 4px 0px 0px 0px;">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                        The advertisements on the King County Assessor’s eReal Property website are part of a pilot program to
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    test the viability of web ads on the site. The goal of the ads is to generate revenue to support
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                department operations and taxpayer services. Advertisements are placed in accordance with the Department
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            of Assessments' guidelines for web advertising.
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br><br>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    An important part of our work is to gather public feedback and to make sure the advertising does not
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                interfere with the viewing or navigation of the Assessor's website. If you have any questions or comments,
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            we encourage you to send them to: <a href="mailto:web.ads@kingcounty.gov">web.ads@kingcounty.gov</a>.  We want to hear from you.
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                            //
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                            //
                            //
                            //
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <br>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <!-- /22447532351/King-County:desktop:multiple-sizes:bottom -->
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div id="div-gpt-ad-1444144432012-2">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <script type="text/javascript">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           googletag.cmd.push(function() { googletag.display('div-gpt-ad-1444144432012-2'); });
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </script>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div style="text-align: right;width:728px;">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <a id="cphContent_LinkButtonAds2" title="ADVERTISEMENT" href="javascript:__doPostBack('kingcounty_gov$cphContent$LinkButtonAds2','')" style="font-weight:bold;">ADVERTISEMENT</a>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                            //
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </td><td id="rightcol" class="column">
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <table>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <tbody><tr valign="top">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <td>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <!-- /22447532351/King-County:desktop:160x600:rhs -->
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div id="div-gpt-ad-1444144432012-1" style="height:600px; width:160px;float:right;">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <script type="text/javascript">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        googletag.cmd.push(function() { googletag.display('div-gpt-ad-1444144432012-1'); });
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </script>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div style="text-align: right;">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <a id="cphRight_LinkButtonAds3" title="ADVERTISEMENT" href="javascript:__doPostBack('kingcounty_gov$cphRight$LinkButtonAds3','')" style="font-weight:bold;">ADVERTISEMENT</a>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </td>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <td>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="spot">
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <h2>Reference Links:</h2>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <ul>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <li><a href="https://www.kingcounty.gov/services/home-property.aspx" target="_blank">King County Tax Links</a><br><br></li>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <li><a href="https://www.kingcounty.gov/independent/property-tax-advisor.aspx" target="_blank">Property Tax Advisor</a><br><br></li>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <li><a href="https://dor.wa.gov/" target="_blank">Washington State Department of Revenue</a>  (External link)<br><br></li>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <li><a href="https://bta.state.wa.us/" target="_blank">Washington State Board of Tax Appeals</a>  (External link)<br><br></li>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <li><a href="https://www.kingcounty.gov/property/PropertyTaxAppeals.aspx" target="_blank">Board of Appeals/Equalization</a><br><br></li>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <li><a id="cphRight_HyperLinkDistrictDevelopmentCondition" title="This links to King County GIS Districts and Development Conditions Report" href="https://www5.kingcounty.gov/kcgisreports/dd_report.aspx" target="_blank">Districts Report</a><br><br></li>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <li><a id="cphRight_HyperLinkParcelViewer" href="https://gismaps.kingcounty.gov/parcelviewer2/" target="_blank" style="display:inline-block;width:158px;">Parcel Viewer (map)</a><br><br></li>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <li><a id="cphRight_HyperLinkIMap" title="This links to King County GIS IMap" href="https://www5.kingcounty.gov/iMAP/viewer.htm" target="_blank">iMap</a><br><br></li>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <li><a href="https://www.kingcounty.gov/business/Recorders.aspx" target="_blank">Recorder's Office</a><br><br></li>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </ul>
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </td>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </tr>
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </tbody></table>
                            //
                            //
                            //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         &nbsp;       </td></tr></tbody></table>
                        })
            */
